### ISSUE TITLE
About testing signing (test-hw-sign.prg)

### ISSUE THREAD

**Issue by jhernancanom** [atlopes/xml#1]
Good morning, friend.

I am running the sample **test-hw-sign.prg** with **hw-H.xml** (attached), that is a _hw.xml_ modified. The mod is adding this tag:

`<ext:UBLExtensions><ext:UBLExtension><ext:ExtensionContent></ext:ExtensionContent></ext:UBLExtension></ext:UBLExtensions>`

My intent is trying to get the signing stayed inside <ext:ExtensionContent></ext:ExtensionContent> because that is the requirement in my country.

Is there a way that the resulting signing get in (1) an external file, or (2) as a char memory string, or (3) at the very end of the XML to sign, or something so?

Thanks.

**HERNAN CANO**
Systems Analyst

[test-hw-sign-H.zip](https://github.com/atlopes/xml/files/6293893/test-hw-sign-H.zip)

**Comment by atlopes** [comment]
Hernan,

You can place the signature anywhere in the XML document, just pass the position to the `AppendSignature()` method.

To place the signature inside the ExtensionContent element:
 
```foxpro
m.XML.setProperty("SelectionNamespaces", 'xmlns:e="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"')

LOCAL ExtensionContent AS MSXML2.IXMLDOMElement

m.ExtensionContent = m.XML.selectNodes("//Invoice/e:UBLExtensions/e:UBLExtension/e:ExtensionContent").item(0)

m.DSig.AppendSignature(m.ExtensionContent)
```

Since the Signature element becomes an element of the XML document, you can do with it what you normally do with other elements. But you'll have to make sure that the Signature contents do not change a single byte for it to remain effective.

**Comment by jhernancanom** [comment]
Yes, Antonio.It runs fine, as I need.
I used the **e:** in the XPath route you said, and it runs fine (my XML has **ext:** as prefix for the Extension tags).
Thanks.
I´ll continue with my proofs and talk to you.
Very grateful......

**Comment by atlopes** [comment]
Great to hear, Hernan.

You can use the prefix of your choice as long as it references the proper namespace.
